<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260417115005 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE IF EXISTS messenger_messages');
        $this->addSql('ALTER TABLE booking ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE booking ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE booking ALTER status DROP DEFAULT');
        $this->addSql('ALTER INDEX uq_booking_idempotency RENAME TO UNIQ_E00CEDDE7FD1C147');
        $this->addSql('ALTER INDEX idx_booking_user RENAME TO IDX_E00CEDDEA76ED395');
        $this->addSql('ALTER INDEX idx_booking_event RENAME TO IDX_E00CEDDE71F7E88B');
        $this->addSql('ALTER TABLE booking_item DROP CONSTRAINT fk_item_booking');
        $this->addSql('ALTER TABLE booking_item ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE booking_item ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE booking_item ADD CONSTRAINT FK_78A07503301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_item_booking RENAME TO IDX_78A07503301C60');
        $this->addSql('ALTER INDEX uq_item_reservation RENAME TO UNIQ_78A07504E2DED1B');
        $this->addSql('ALTER TABLE category ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE category ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uq_category_name RENAME TO UNIQ_64C19C15E237E06');
        $this->addSql('ALTER TABLE e_ticket ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE e_ticket ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX uq_eticket_qrtoken RENAME TO UNIQ_ED6E4E81AE26361');
        $this->addSql('ALTER INDEX uq_eticket_item RENAME TO UNIQ_ED6E4E848D1177E');
        $this->addSql('ALTER TABLE error_log ADD exception_class VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE error_log ADD stack_trace TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE error_log ADD method VARCHAR(10) NOT NULL');
        $this->addSql('ALTER TABLE error_log ADD status_code INT NOT NULL');
        $this->addSql('ALTER TABLE error_log ADD user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE error_log ADD ip_address VARCHAR(45) DEFAULT NULL');
        $this->addSql('ALTER TABLE error_log ADD occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE error_log ADD resolved BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE error_log ADD admin_note TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE error_log DROP level');
        $this->addSql('ALTER TABLE error_log DROP context');
        $this->addSql('ALTER TABLE error_log DROP created_at');
        $this->addSql('ALTER TABLE error_log ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE error_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE error_log ALTER message TYPE VARCHAR(500)');
        $this->addSql('CREATE INDEX idx_error_log_occurred_status ON error_log (occurred_at, status_code)');
        $this->addSql('DROP INDEX uniq_events_slug');
        $this->addSql('DROP INDEX idx_event_status');
        $this->addSql('DROP INDEX idx_event_datetime');
        $this->addSql('ALTER TABLE events ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE events ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE events ALTER is_online DROP DEFAULT');
        $this->addSql('ALTER TABLE events ALTER status DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_event_organizer RENAME TO IDX_5387574A876C4DDA');
        $this->addSql('ALTER INDEX idx_event_category RENAME TO IDX_5387574A12469DE2');
        $this->addSql('ALTER TABLE organizer ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE organizer ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE organizer ALTER approval_status DROP DEFAULT');
        $this->addSql('ALTER INDEX uq_organizer_user RENAME TO UNIQ_99D47173A76ED395');
        $this->addSql('ALTER TABLE seat DROP CONSTRAINT fk_seat_event');
        $this->addSql('ALTER TABLE seat ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE seat ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE seat ALTER is_assigned DROP DEFAULT');
        $this->addSql('ALTER TABLE seat ADD CONSTRAINT FK_3D5C366671F7E88B FOREIGN KEY (event_id) REFERENCES events (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE seat_reservation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE seat_reservation ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE seat_reservation ALTER status DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_reservation_user RENAME TO IDX_6793F25FA76ED395');
        $this->addSql('ALTER TABLE ticket_tier DROP CONSTRAINT fk_tier_event');
        $this->addSql('ALTER TABLE ticket_tier ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ticket_tier ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE ticket_tier ALTER sold_count DROP DEFAULT');
        $this->addSql('ALTER TABLE ticket_tier ADD CONSTRAINT FK_164582B271F7E88B FOREIGN KEY (event_id) REFERENCES events (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_tier_event RENAME TO IDX_164582B271F7E88B');
        $this->addSql('ALTER TABLE transaction ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE transaction ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_transaction_user RENAME TO IDX_723705D1A76ED395');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE users ALTER role DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER credit_balance DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER timezone DROP DEFAULT');
        $this->addSql('ALTER INDEX uq_users_email RENAME TO UNIQ_1483A5E9E7927C74');
        $this->addSql('ALTER INDEX uniq_users_pending_email RENAME TO UNIQ_1483A5E97807FE7C');
        $this->addSql('ALTER INDEX uniq_users_verification_token RENAME TO UNIQ_1483A5E9C1CC006B');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_75ea56e0fb7336f0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX idx_75ea56e0e3bd61ce ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX idx_75ea56e016ba31db ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE booking ALTER id SET DEFAULT nextval(\'booking_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE booking ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE booking ALTER status SET DEFAULT \'confirmed\'');
        $this->addSql('ALTER INDEX uniq_e00cedde7fd1c147 RENAME TO uq_booking_idempotency');
        $this->addSql('ALTER INDEX idx_e00cedde71f7e88b RENAME TO idx_booking_event');
        $this->addSql('ALTER INDEX idx_e00ceddea76ed395 RENAME TO idx_booking_user');
        $this->addSql('ALTER TABLE booking_item DROP CONSTRAINT FK_78A07503301C60');
        $this->addSql('ALTER TABLE booking_item ALTER id SET DEFAULT nextval(\'booking_item_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE booking_item ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE booking_item ADD CONSTRAINT fk_item_booking FOREIGN KEY (booking_id) REFERENCES booking (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX uniq_78a07504e2ded1b RENAME TO uq_item_reservation');
        $this->addSql('ALTER INDEX idx_78a07503301c60 RENAME TO idx_item_booking');
        $this->addSql('ALTER TABLE category ALTER id SET DEFAULT nextval(\'category_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE category ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_64c19c15e237e06 RENAME TO uq_category_name');
        $this->addSql('ALTER TABLE e_ticket ALTER id SET DEFAULT nextval(\'e_ticket_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE e_ticket ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_ed6e4e848d1177e RENAME TO uq_eticket_item');
        $this->addSql('ALTER INDEX uniq_ed6e4e81ae26361 RENAME TO uq_eticket_qrtoken');
        $this->addSql('DROP INDEX idx_error_log_occurred_status');
        $this->addSql('ALTER TABLE error_log ADD level VARCHAR(20) DEFAULT \'error\' NOT NULL');
        $this->addSql('ALTER TABLE error_log ADD context JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE error_log ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE error_log DROP exception_class');
        $this->addSql('ALTER TABLE error_log DROP stack_trace');
        $this->addSql('ALTER TABLE error_log DROP method');
        $this->addSql('ALTER TABLE error_log DROP status_code');
        $this->addSql('ALTER TABLE error_log DROP user_id');
        $this->addSql('ALTER TABLE error_log DROP ip_address');
        $this->addSql('ALTER TABLE error_log DROP occurred_at');
        $this->addSql('ALTER TABLE error_log DROP resolved');
        $this->addSql('ALTER TABLE error_log DROP admin_note');
        $this->addSql('ALTER TABLE error_log ALTER id SET DEFAULT nextval(\'error_log_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE error_log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE error_log ALTER message TYPE TEXT');
        $this->addSql('COMMENT ON COLUMN error_log.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE events ALTER id SET DEFAULT nextval(\'events_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE events ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE events ALTER is_online SET DEFAULT false');
        $this->addSql('ALTER TABLE events ALTER status SET DEFAULT \'active\'');
        $this->addSql('CREATE UNIQUE INDEX uniq_events_slug ON events (slug)');
        $this->addSql('CREATE INDEX idx_event_status ON events (status)');
        $this->addSql('CREATE INDEX idx_event_datetime ON events (date_time)');
        $this->addSql('ALTER INDEX idx_5387574a876c4dda RENAME TO idx_event_organizer');
        $this->addSql('ALTER INDEX idx_5387574a12469de2 RENAME TO idx_event_category');
        $this->addSql('ALTER TABLE organizer ALTER id SET DEFAULT nextval(\'organizer_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE organizer ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE organizer ALTER approval_status SET DEFAULT \'pending\'');
        $this->addSql('ALTER INDEX uniq_99d47173a76ed395 RENAME TO uq_organizer_user');
        $this->addSql('ALTER TABLE seat DROP CONSTRAINT FK_3D5C366671F7E88B');
        $this->addSql('ALTER TABLE seat ALTER id SET DEFAULT nextval(\'seat_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE seat ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE seat ALTER is_assigned SET DEFAULT false');
        $this->addSql('ALTER TABLE seat ADD CONSTRAINT fk_seat_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE seat_reservation ALTER id SET DEFAULT nextval(\'seat_reservation_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE seat_reservation ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE seat_reservation ALTER status SET DEFAULT \'pending\'');
        $this->addSql('ALTER INDEX idx_6793f25fa76ed395 RENAME TO idx_reservation_user');
        $this->addSql('ALTER TABLE ticket_tier DROP CONSTRAINT FK_164582B271F7E88B');
        $this->addSql('ALTER TABLE ticket_tier ALTER id SET DEFAULT nextval(\'ticket_tier_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE ticket_tier ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE ticket_tier ALTER sold_count SET DEFAULT 0');
        $this->addSql('ALTER TABLE ticket_tier ADD CONSTRAINT fk_tier_event FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER INDEX idx_164582b271f7e88b RENAME TO idx_tier_event');
        $this->addSql('ALTER TABLE transaction ALTER id SET DEFAULT nextval(\'transaction_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE transaction ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_723705d1a76ed395 RENAME TO idx_transaction_user');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE users ALTER role SET DEFAULT \'ROLE_USER\'');
        $this->addSql('ALTER TABLE users ALTER credit_balance SET DEFAULT 2000');
        $this->addSql('ALTER TABLE users ALTER timezone SET DEFAULT \'UTC\'');
        $this->addSql('ALTER INDEX uniq_1483a5e9c1cc006b RENAME TO uniq_users_verification_token');
        $this->addSql('ALTER INDEX uniq_1483a5e9e7927c74 RENAME TO uq_users_email');
        $this->addSql('ALTER INDEX uniq_1483a5e97807fe7c RENAME TO uniq_users_pending_email');
    }
}
