<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260419000002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add check-in fields to e_ticket, waitlist table, and full-text search vector to events';
    }

    public function up(Schema $schema): void
    {
        // --- Check-in fields on e_ticket ---
        $this->addSql('ALTER TABLE e_ticket ADD checked_in_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE e_ticket ADD checked_in_by INT DEFAULT NULL');
        $this->addSql('ALTER TABLE e_ticket ADD CONSTRAINT FK_CHECKIN_BY FOREIGN KEY (checked_in_by) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_eticket_checkin ON e_ticket (checked_in_at)');

        // --- Waitlist table ---
        $this->addSql('CREATE TABLE waitlist (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            event_id INT NOT NULL,
            ticket_tier_id INT NOT NULL,
            joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            notified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            status VARCHAR(20) NOT NULL DEFAULT \'pending\',
            PRIMARY KEY(id)
        )');
        $this->addSql('ALTER TABLE waitlist ADD CONSTRAINT FK_WL_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE waitlist ADD CONSTRAINT FK_WL_EVENT FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE waitlist ADD CONSTRAINT FK_WL_TIER FOREIGN KEY (ticket_tier_id) REFERENCES ticket_tier (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX uq_waitlist_user_tier ON waitlist (user_id, ticket_tier_id) WHERE status = \'pending\'');
        $this->addSql('CREATE INDEX idx_waitlist_tier_status ON waitlist (ticket_tier_id, status)');
        $this->addSql('CREATE INDEX idx_waitlist_user ON waitlist (user_id)');

        // --- Full-text search vector on events ---
        $this->addSql("ALTER TABLE events ADD COLUMN search_vector tsvector GENERATED ALWAYS AS (to_tsvector('english', name || ' ' || coalesce(description, ''))) STORED");
        $this->addSql('CREATE INDEX idx_events_search ON events USING GIN(search_vector)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX idx_events_search');
        $this->addSql('ALTER TABLE events DROP COLUMN search_vector');

        $this->addSql('ALTER TABLE waitlist DROP CONSTRAINT FK_WL_USER');
        $this->addSql('ALTER TABLE waitlist DROP CONSTRAINT FK_WL_EVENT');
        $this->addSql('ALTER TABLE waitlist DROP CONSTRAINT FK_WL_TIER');
        $this->addSql('DROP TABLE waitlist');

        $this->addSql('ALTER TABLE e_ticket DROP CONSTRAINT FK_CHECKIN_BY');
        $this->addSql('DROP INDEX idx_eticket_checkin');
        $this->addSql('ALTER TABLE e_ticket DROP checked_in_at');
        $this->addSql('ALTER TABLE e_ticket DROP checked_in_by');
    }
}
